// AUTO-GENERATED by update_scores.py — do not edit manually
export const LAST_UPDATED = "23 June 2026 · after 46 matches";

export const PLAYERS = [
  { name: "Lottie", color: "#40C6A0", total: 26, played: 11, teams: "Mexico (6), Argentina (6), Morocco (4), Netherlands (4), Paraguay (3), England (3)" },
  { name: "Sam", color: "#FF9F43", total: 21, played: 11, teams: "France (6), Norway (6), Spain (4), Sweden (3), Uruguay (2), Uzbekistan (0)" },
  { name: "Tom", color: "#F0C446", total: 18, played: 12, teams: "USA (6), Brazil (4), Australia (3), Ivory Coast (3), Saudi Arabia (1), Bosnia (1)" },
  { name: "Joanne", color: "#E0556E", total: 15, played: 11, teams: "Germany (6), Canada (4), Colombia (3), South Africa (1), Curaçao (1), Tunisia (0)" },
  { name: "Joe", color: "#5896FF", total: 13, played: 11, teams: "Japan (4), South Korea (3), Belgium (2), Iran (2), Czechia (1), DR Congo (1)" },
  { name: "Matt", color: "#C77DFF", total: 13, played: 12, teams: "Egypt (4), Scotland (3), Austria (3), Algeria (3), Senegal (0), Iraq (0)" },
  { name: "Darrell", color: "#9DB2BF", total: 9, played: 10, teams: "Switzerland (4), Ghana (3), Ecuador (1), Portugal (1), Haiti (0), Panama (0)" },
  { name: "Karina", color: "#4ECDC4", total: 4, played: 11, teams: "Cape Verde (2), Qatar (1), New Zealand (1), Turkiye (0), Jordan (0), Croatia (0)" }
];

export const PROGRESSION = [
  { day: "Start", Lottie: 0, Tom: 0, Sam: 0, Joanne: 0, Joe: 0, Darrell: 0, Matt: 0, Karina: 0 },
  { day: "11 Jun", Lottie: 3, Tom: 0, Sam: 0, Joanne: 0, Joe: 0, Darrell: 0, Matt: 0, Karina: 0 },
  { day: "12 Jun", Lottie: 3, Tom: 0, Sam: 0, Joanne: 1, Joe: 3, Darrell: 0, Matt: 0, Karina: 0 },
  { day: "13 Jun", Lottie: 4, Tom: 4, Sam: 0, Joanne: 1, Joe: 3, Darrell: 1, Matt: 0, Karina: 1 },
  { day: "14 Jun", Lottie: 5, Tom: 10, Sam: 0, Joanne: 4, Joe: 4, Darrell: 1, Matt: 3, Karina: 1 },
  { day: "15 Jun", Lottie: 5, Tom: 11, Sam: 5, Joanne: 4, Joe: 5, Darrell: 1, Matt: 4, Karina: 1 },
  { day: "16 Jun", Lottie: 5, Tom: 11, Sam: 11, Joanne: 4, Joe: 6, Darrell: 1, Matt: 4, Karina: 2 },
  { day: "17 Jun", Lottie: 11, Tom: 11, Sam: 11, Joanne: 4, Joe: 6, Darrell: 5, Matt: 7, Karina: 2 },
  { day: "18 Jun", Lottie: 11, Tom: 11, Sam: 11, Joanne: 11, Joe: 7, Darrell: 8, Matt: 7, Karina: 2 },
  { day: "19 Jun", Lottie: 17, Tom: 14, Sam: 11, Joanne: 11, Joe: 7, Darrell: 8, Matt: 7, Karina: 2 },
  { day: "20 Jun", Lottie: 23, Tom: 17, Sam: 11, Joanne: 14, Joe: 7, Darrell: 8, Matt: 7, Karina: 2 },
  { day: "21 Jun", Lottie: 23, Tom: 18, Sam: 15, Joanne: 15, Joe: 13, Darrell: 9, Matt: 7, Karina: 4 },
  { day: "22 Jun", Lottie: 26, Tom: 18, Sam: 15, Joanne: 15, Joe: 13, Darrell: 9, Matt: 10, Karina: 4 },
  { day: "23 Jun", Lottie: 26, Tom: 18, Sam: 21, Joanne: 15, Joe: 13, Darrell: 9, Matt: 13, Karina: 4 }
];

export const RECENT = [
  { a: "Norway", ga: 3, gb: 2, b: "Senegal" },
  { a: "France", ga: 3, gb: 0, b: "Iraq" },
  { a: "Algeria", ga: 2, gb: 1, b: "Jordan" },
  { a: "Argentina", ga: 2, gb: 0, b: "Austria" }
];
