// AUTO-GENERATED by update_scores.py — do not edit manually
export const LAST_UPDATED = "28 June 2026 · Round of 32 underway";

export const PLAYERS = [
  { name: "Lottie", color: "#40C6A0", total: 43, played: 18, teams: "Mexico (9), Argentina (9), Morocco (7), Netherlands (7), England (7), Paraguay (4)" },
  { name: "Tom", color: "#F0C446", total: 29, played: 18, teams: "Brazil (7), USA (6), Ivory Coast (6), Bosnia (4), Australia (4), Saudi Arabia (2)" },
  { name: "Sam", color: "#FF9F43", total: 28, played: 18, teams: "France (9), Spain (7), Norway (6), Sweden (4), Uruguay (2), Uzbekistan (0)" },
  { name: "Joanne", color: "#E0556E", total: 25, played: 19, teams: "Colombia (7), Canada (7), Germany (6), South Africa (4), Curaçao (1), Tunisia (0)" },
  { name: "Joe", color: "#5896FF", total: 21, played: 18, teams: "Japan (5), Belgium (5), DR Congo (4), South Korea (3), Iran (3), Czechia (1)" },
  { name: "Darrell", color: "#9DB2BF", total: 20, played: 18, teams: "Switzerland (7), Portugal (5), Ghana (4), Ecuador (4), Haiti (0), Panama (0)" },
  { name: "Matt", color: "#C77DFF", total: 19, played: 18, teams: "Egypt (5), Austria (4), Algeria (4), Scotland (3), Senegal (3), Iraq (0)" },
  { name: "Karina", color: "#4ECDC4", total: 14, played: 18, teams: "Croatia (6), Cape Verde (3), Turkiye (3), Qatar (1), New Zealand (1), Jordan (0)" }
];

export const PROGRESSION = [
  { day: "Start", Lottie: 0, Tom: 0, Sam: 0, Joanne: 0, Joe: 0, Darrell: 0, Matt: 0, Karina: 0 },
  { day: "11 Jun", Lottie: 3, Tom: 0, Sam: 0, Joanne: 0, Joe: 0, Darrell: 0, Matt: 0, Karina: 0 },
  { day: "12 Jun", Lottie: 3, Tom: 0, Sam: 0, Joanne: 1, Joe: 3, Darrell: 0, Matt: 0, Karina: 0 },
  { day: "13 Jun", Lottie: 4, Tom: 4, Sam: 0, Joanne: 1, Joe: 3, Darrell: 1, Matt: 0, Karina: 1 },
  { day: "14 Jun", Lottie: 5, Tom: 10, Sam: 0, Joanne: 4, Joe: 4, Darrell: 1, Matt: 3, Karina: 1 },
  { day: "15 Jun", Lottie: 5, Tom: 11, Sam: 5, Joanne: 4, Joe: 5, Darrell: 1, Matt: 4, Karina: 1 },
  { day: "16 Jun", Lottie: 5, Tom: 11, Sam: 11, Joanne: 4, Joe: 6, Darrell: 1, Matt: 4, Karina: 2 },
  { day: "17 Jun", Lottie: 11, Tom: 11, Sam: 11, Joanne: 4, Joe: 6, Darrell: 5, Matt: 7, Karina: 2 },
  { day: "18 Jun", Lottie: 11, Tom: 11, Sam: 11, Joanne: 11, Joe: 7, Darrell: 8, Matt: 7, Karina: 2 },
  { day: "19 Jun", Lottie: 17, Tom: 14, Sam: 11, Joanne: 11, Joe: 7, Darrell: 8, Matt: 7, Karina: 2 },
  { day: "20 Jun", Lottie: 23, Tom: 17, Sam: 11, Joanne: 14, Joe: 7, Darrell: 8, Matt: 7, Karina: 2 },
  { day: "21 Jun", Lottie: 23, Tom: 18, Sam: 15, Joanne: 15, Joe: 13, Darrell: 9, Matt: 7, Karina: 4 },
  { day: "22 Jun", Lottie: 26, Tom: 18, Sam: 15, Joanne: 15, Joe: 13, Darrell: 9, Matt: 10, Karina: 4 },
  { day: "23 Jun", Lottie: 27, Tom: 18, Sam: 21, Joanne: 18, Joe: 13, Darrell: 13, Matt: 13, Karina: 7 },
  { day: "24 Jun", Lottie: 33, Tom: 24, Sam: 21, Joanne: 21, Joe: 13, Darrell: 16, Matt: 13, Karina: 7 },
  { day: "25 Jun", Lottie: 37, Tom: 28, Sam: 22, Joanne: 21, Joe: 14, Darrell: 19, Matt: 13, Karina: 10 },
  { day: "26 Jun", Lottie: 37, Tom: 29, Sam: 28, Joanne: 21, Joe: 18, Darrell: 19, Matt: 17, Karina: 11 },
  { day: "27 Jun", Lottie: 43, Tom: 29, Sam: 28, Joanne: 22, Joe: 21, Darrell: 20, Matt: 19, Karina: 14 }
];

export const RECENT = [
  { a: "Canada", ga: 1, gb: 0, b: "South Africa" }
];
